config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :links, except: :index

  # get "link/new", to: "links#new"
  # post "link", to: "links#create"
  # delete "link/:id", to: "links#destroy"

  root 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :links, dependent: :destroy
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :set_links_columns]
  before_action :set_category_columns, only: [:index, :new]
  before_action :set_links_columns, only: [:show]

  def index
    @categories = Category.all.order(:name)
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to categories_path
  end

  def show
    # raise
    @links = @category.links.all.order(:name)
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to category_path
  end

  private

  # def set_category
  #   @category = Category.find(params[:id])
  # end

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def set_category_columns
    @categories = Category.all
    count = @categories.count
    if count / 8 == 0
      @category_columns_count = 1
    else
      @category_columns_count = count / 8 + 1
    end
  end

  def set_links_columns
    @links = @category.links.all
    count = @links.count
    if count / 8 == 0
      @links_columns_count = 1
    else
      @links_columns_count = count / 8 + 1
    end
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:edit, :update, :destroy]
  before_action :set_category_columns, only: [:new]
# no index method needed

  def index
    @links = Link.all
  end

  def new
    @link = Link.new
    @categories = Category.all
  end

  def create
    @link = Link.new(link_params)
    @link.save
    redirect_to categories_path
  end

  def edit
    @categories = Category.all
  end

  def update
    @link.update(link_params)
    redirect_to root_path
  end

  def destroy
    # @category = @link.category
    @link.destroy
    redirect_to root_path
    # raise
  end

  private

  def link_params
    params.require(:link).permit(:name, :url, :category_id)
  end

  def set_link
    @link = Link.find(params[:id])
  end

  def set_category_columns
    @categories = Category.all
    count = @categories.count
    if count / 8 == 0
      @category_columns_count = 1
    else
      @category_columns_count = count / 8 + 1
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/categories/_form.html.erb
<div class="form">
  <%= form_for @category do |x| %>
    <%= x.text_field(:name) %>
    <%= x.label(:name) %>
    <%= x.submit("Submit") %>
  <% end  %>
</div>

app/views/categories/edit.html.erb
<h1>Edit the Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="container">
  <div class="header">
    <div class="header_item" style="margin-left: 2%">
      <%= link_to "Add a Category", new_category_path %>
    </div>
    <div class="header_item">
      <h1>Eve Resources Tool</h1>
    </div>
    <div class="header_item" style="margin-right: 2%">
      <%= link_to "Add a New Link", new_link_path %>
    </div>
  </div>

  <div class="content_div">
    <div class="content">
      <ul style="columns: <%= @category_columns_count %>">
        <% @categories.each do |category| %>
        <li>
          <%= link_to "#{category.name}", category_path(category.id) %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="header">
    <div class="header_item" style="margin-left: 2%">
      <%= link_to "Back to Start", root_path %>
    </div>
    <div class="header_item">
      <h1>Add New Category</h1>
    </div>
    <div class="header_item" style="margin-right: 2%">
      <%= link_to "Add a New Link", new_link_path %>
    </div>
  </div>

  <div class="content_div">
    <div class="content">
      <%= render 'form' %>

      <h2 style="margin-top: 2.5em">Existing Categories</h2>

      <ul style="columns: <%= @category_columns_count %>">
        <% @categories.each do |category| %>
        <li>
          <%= category.name %>
          <!-- <%= link_to "Edit", edit_category_path(category.id) %> -->
        </li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="header">
    <div class="header_item" style="margin-left: 2%">
      <%= link_to "Back to Start", root_path %>
    </div>
    <div class="header_item">
      <h1><%= @category.name %></h1>
    </div>
    <div class="header_item" style="margin-right: 2%">
      <%= link_to "Add a New Link", new_link_path %>
    </div>
  </div>

  <div class="content_div">
    <div class="content">
      <ul style="columns: <%= @links_columns_count %>">
        <% @links.each do |link| %>
          <li>
            <a href="<%= link.url %>" target="_blank"><%= link.name %></a>
            <!-- <%= link_to image_tag("edit.svg", class: "edit-icon"), edit_link_path(link.id) %> -->
            <%= link_to image_tag("trash.png", class: "trash-icon"), link_path(link.id), method: :delete, confirm: "Are you sure?" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostgresTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |x| %>
  <%= x.label(:name) %>
  <%= x.text_field(:name) %>
  <%= x.label(:url) %>
  <%= x.text_field(:url) %>
  <ul style="columns: <%= @category_columns_count %>">
    <% @categories.each do |category| %>
      <li>
        <!-- radio_button(object_name, method, tag_value, options={}) -->
        <%= x.radio_button :category_id, category.id %>
        <%= x.label :category_id, "#{category.name}" %>
      </li>
    <% end %>
  </ul>
  <%= x.submit("Submit") %>
<% end %>

app/views/links/edit.html.erb
<!-- Here I would want to have buttons/radio buttons with existing category names to click when creating a new link
entry that would pass that category_id with the other params to create new instance.
Would also want to have a button that says 'click here to add new category if your desired one is not available
and that would link_to categories#new' -->

<%= link_to image_tag("star.svg", width: 50), root_path %>

<h1>Add New Resource</h1>

<%= render 'form' %>

<p>Don't see the category you're looking for? Click <%= link_to "here", new_category_path %> to add it to the list </p>

app/views/links/index.html.erb
<h1>Links</h1>

<ul>
  <% @links.each do |link| %>
    <li>
      <a href="<%= link.url %>"><%= link.name %></a>
    </li>
  <% end %>
</ul>

app/views/links/new.html.erb
<!-- Here I would want to have buttons/radio buttons with existing category names to click when creating a new link
entry that would pass that category_id with the other params to create new instance.
Would also want to have a button that says 'click here to add new category if your desired one is not available
and that would link_to categories#new' -->

<div class="container">
  <div class="header">
    <div class="header_item" style="margin-left: 2%">
      <%= link_to "Back to Start", root_path %>
    </div>
    <div class="header_item">
      <h1>Add New Link</h1>
    </div>
    <div class="header_item" style="margin-right: 2%">
      <%= link_to "Add a New Category", new_category_path %>
    </div>
  </div>

  <div class="content_div">
    <div class="content">
      <%= render 'form' %>
    </div>
  </div>
</div>



<p style="color: white; margin-top: 4em; margin-left: 1em">Click "Add a New Category" at the top right if you don't see the category you want/need for your link.</p>